# _config.yml
title: "Angel Rodas's Portfolio"
author: "Angel Rodas"
description: "Mechanical & Aerospace MS Student | UC Davis HRVIP Lab"

# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "neon"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

# Basic site Settings
title: "Angel Rodas's Portfolio"
description: "A landing page for some of my projects"
url: "https://username.github.io" 
baseurl: "" 

show_downloads: false          
github:
  is_project_page: false
  is_user_page: false
